site_name: NXT User Docs
site_description: Node eXecution Tree, A python layering and sequential execution tool for Animation and VFX
copyright: 2020 NXT authors

nav:
    - Home: index.md
    - Concepts: concepts.md
    - Tutorials: tutorials.md
    - Installation: install.md
    - Reference: reference.md
    - Extensions: extensions.md
    - API: api/index.html
    - License: license.md
    - About: about.md

markdown_extensions:
  - admonition

theme:
  # name: material
  name: mkdocs
  highlightjs: true
  hljs_style: tomorrow-night
  hljs_languages:
      - yaml
      - json
      - python
  custom_dir: custom_theme/

# extra_css: [extra.css]

